### ISSUE TITLE
Restrict Navigation Bar Links Based on User Authentication Status

### ISSUE THREAD

**Issue by bbland1** [the-collab-lab/tcl-77-smart-shopping-list#26]
#### Description
We utilize Google Auth in the app to validate users are seeing their own lists and items, and it's awesome. When working on issue #5 we noticed that in some troubleshooting that while the user is needed to access the lists and the form on the manage list page a user could navigate to their like base pages. It caused some "it works on my computer" moments with trying to just use the form without signing in first since you can navigate to the page. It seems that making sure the nav bar utilizes the user object somehow like the signin/sign out button would be a better flow for users.

#### Acceptance Criteria
- [x] The sign in button is on the homepage when no user is logged in
- [x] The sign out button is in the nav bar when a user is logged in and there is no sign in button
- [x] The nav bar is only visible when a user is logged in
- [x] Prevent manual navigation to routes that a user has to be logged into see

#### Screenshots
The screenshots are on mobile because I was just making sure it worked there too when it was noticed again after the issue. I can click those links and see those pages. The parts that are protected by the user aren't there but I think it may be nice to have those parts of the navbar not show up if no one is logged in since the are specific to the app.

https://github.com/user-attachments/assets/6379de02-3372-4e7b-a357-2f6153089377

#### Files
To make the changes the files affected would be 🤔:
- `App.tsx`
- `Layout.tsx`
- `useAuth.tsx`?

#### To Reproduce
When navigating to the application if you are not logged in you will be able to click all the navlinks because they will display and it will say the "hi from this page" on each of them.

#### Tasks
- [x] In the `Layout` component in the `App.tsx` the user prop could be added and pass the user info the app gets from calling the `useAuth` function, and use that for th user checks instead of calling useAuth again.
- [x] Move the sign in button out of the nav bar so on the home page it can display on the page when a user is not signed in. Maybe into the main tag right now and change the check to be something like `!!user ? null : <SignInButton />` so that if the user isn't logged the button will be the sign in version.
- [x] Have the NavBar show based on if a user is sign in out not by using the same user check that is currently on the sign in button but for the nav bar. Surrounding the navbar in a user check with `user ? NAV BAR : null`. The signout button in the nav bar would stay but the check would change to something like `!!user ? <SignOutButton /> : null` 
- [x] The sign out button in `useAuth.tsx` would probably need to be updated to redirect/ navigate the page back to the home page if a user is on the list or manage list page when they hit the signout button.

**Comment by tannaurus** [comment]
I love this idea! One thing to keep in mind: hiding the navigation bar is enough to communicate what is/isn't possible from one perspective, but a crafty user may try to work their way around it. You might want to consider adding a check to each "view" that redirects back to `Home` if the user isn't signed in. The desired functionality should immediately redirect the user back to `/` if they attempt to manually visit `/list` (or another "protected route") while unauthenticated,

**Comment by bbland1** [comment]
> I love this idea! One thing to keep in mind: hiding the navigation bar is enough to communicate what is/isn't possible from one perspective, but a crafty user may try to work their way around it. You might want to consider adding a check to each "view" that redirects back to `Home` if the user isn't signed in. The desired functionality should immediately redirect the user back to `/` if they attempt to manually visit `/list` (or another "protected route") while unauthenticated.

Such a good point! Really make sure to see the scope of the issue other than just the view! Thank you so much!
